package com.example.feedsense.analysis.ml.preprocess.golden

import com.example.feedsense.analysis.ml.preprocess.FrameOrientation
import com.example.feedsense.analysis.ml.preprocess.PreprocessingConfig
import com.example.feedsense.analysis.ml.preprocess.PreprocessFailureCode

// --------------------------------
// GOLDEN FIXTURE (8B-15-4)
// --------------------------------
//
// A deterministic, versioned reference case for preprocessing
// reproducibility. A fixture captures everything needed to run one
// preprocessing case and verify its output against known-good
// expectations.
//
// Fixtures are INDEPENDENTLY versioned from the preprocessing
// implementation. A preprocessing change should be distinguishable
// from a fixture-definition change.
//
// Design rules:
//   - no network, no cloud, no external state
//   - synthetic frames only (no real screenshots)
//   - small enough to check into the repository
//   - content-free metadata only (no pixel data in the fixture itself)

/**
 * Comparison policy for floating-point golden outputs.
 *
 * EXACT byte comparison is preferred when the implementation
 * guarantees determinism (same JVM, same locale, same platform).
 * When the implementation uses floating-point arithmetic that
 * could differ across platforms, a documented tolerance is used.
 */
enum class ComparisonPolicy(val label: String) {
    EXACT("EXACT"),
    FLOAT_TOLERANT("FLOAT_TOLERANT")
}

/**
 * Expected output of a preprocessing fixture.
 *
 * Stores the deterministic expectations that the actual output is
 * compared against. When [expectedTensorHash] is present, it is the
 * primary comparison target (byte-level SHA-256 of the serialized
 * tensor). The individual field expectations provide diagnostic
 * detail when a hash mismatch occurs.
 */
data class GoldenExpectation(
    val expectedWidth: Int,
    val expectedHeight: Int,
    val expectedChannels: Int,
    val expectedTensorType: String,
    val expectedLayout: String = "NHWC",
    val expectedDatatype: String = "FLOAT32",
    val expectedTensorHash: String? = null,
    val expectedFingerprint: String? = null,
    val expectedConfigVersion: String = "preprocess-v2",
    val expectedSanitizationStatus: String? = null,
    val expectedFailureCode: PreprocessFailureCode? = null,
    val expectedFailureMessageContains: String? = null,
    val comparisonPolicy: ComparisonPolicy = ComparisonPolicy.EXACT,
    val floatTolerance: Float = 1e-6f,
    val description: String = ""
) {
    val tensorSize: Int get() = expectedWidth * expectedHeight * expectedChannels
}

/**
 * A complete golden fixture: source description + expectations.
 *
 * The fixture does NOT carry the actual input pixels (those are
 * generated by the [GoldenFixtureLoader] from a deterministic
 * synthetic pattern). The fixture carries:
 *   - identity (ID, description, version)
 *   - source characteristics (dimensions, orientation, pattern)
 *   - preprocessing configuration reference
 *   - expected output expectations
 *
 * This separation keeps fixtures small and content-free while the
 * loader generates the actual synthetic input.
 */
data class GoldenFixture(
    val fixtureId: String,
    val description: String,
    val fixtureVersion: String = "1",
    val corpusVersion: String = GoldenFixtureCorpus.CORPUS_VERSION,
    val sourcePattern: SourcePattern,
    val sourceWidth: Int,
    val sourceHeight: Int,
    val sourceOrientation: FrameOrientation = FrameOrientation.DEG_0,
    val configOverride: PreprocessingConfig? = null,
    val expectation: GoldenExpectation,
    val category: FixtureCategory,
    val tags: List<String> = emptyList()
)

/**
 * How the synthetic source frame is generated. Each pattern is
 * fully deterministic given (width, height).
 */
enum class SourcePattern(val label: String) {
    ALL_BLACK("ALL_BLACK"),
    ALL_WHITE("ALL_WHITE"),
    RED_DOMINANT("RED_DOMINANT"),
    GREEN_DOMINANT("GREEN_DOMINANT"),
    BLUE_DOMINANT("BLUE_DOMINANT"),
    RGB_CHANNEL_ISOLATION("RGB_CHANNEL_ISOLATION"),
    GRAYSCALE_LIKE("GRAYSCALE_LIKE"),
    HIGH_CONTRAST_EDGES("HIGH_CONTRAST_EDGES"),
    KNOWN_GRADIENT("KNOWN_GRADIENT"),
    COUNTER_INDEX("COUNTER_INDEX"),
    CHECKERBOARD("CHECKERBOARD"),
    SOLID_ARGB("SOLID_ARGB"),
    PORTRAIT_STRIP("PORTRAIT_STRIP"),
    LANDSCAPE_STRIP("LANDSCAPE_STRIP"),
    SQUARE_SOLID("SQUARE_SOLID"),
    ONE_BY_ONE("ONE_BY_ONE"),
    VERY_SMALL("VERY_SMALL"),
    ODD_DIMENSIONS("ODD_DIMENSIONS"),
    LARGER_THAN_TARGET("LARGER_THAN_TARGET"),
    SMALLER_THAN_TARGET("SMALLER_THAN_TARGET"),
    ALREADY_TARGET_SIZE("ALREADY_TARGET_SIZE"),
    TRANSLUCENT("TRANSLUCENT"),
    SEMI_TRANSPARENT("SEMI_TRANSPARENT")
}

/**
 * Fixture categories for organizing the corpus.
 */
enum class FixtureCategory(val label: String) {
    BASIC_IMAGE("BASIC_IMAGE"),
    ORIENTATION("ORIENTATION"),
    DIMENSION("DIMENSION"),
    PIXEL_PATTERN("PIXEL_PATTERN"),
    CHANNEL_ORDER("CHANNEL_ORDER"),
    ALPHA("ALPHA"),
    RESIZE_CROP_PADDING("RESIZE_CROP_PADDING"),
    NORMALIZATION("NORMALIZATION"),
    DATATYPE_LAYOUT("DATATYPE_LAYOUT"),
    PRIVACY("PRIVACY"),
    NEGATIVE("NEGATIVE"),
    PERFORMANCE_SANITY("PERFORMANCE_SANITY")
}
