package com.example.feedsense.model
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.time.LocalDateTime
import java.util.UUID

@Entity(tableName = "research_observations")
data class ResearchObservation(

    @PrimaryKey
    val id: String = UUID.randomUUID().toString(),

    val sessionId: String,

    val text: String,

    val createdAt: LocalDateTime = LocalDateTime.now(),

    /*
     * Who recorded the observation.
     *
     * - MANUAL : researcher typed it.
     * - AUTO   : generated by the AI pipeline
     *            (Milestone 7C).
     */
    val source: String = SOURCE_MANUAL
) {

    companion object {

        const val SOURCE_MANUAL =
            "MANUAL"

        const val SOURCE_AUTO =
            "AUTO"
    }
}